### ISSUE TITLE
Lab instruction Craft effective Prompts: The screenshots in the instructions are broken and the image is failing to be rendered

### ISSUE THREAD

**Issue by PayalGuruprasad** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#1]
# Module: all the modules in "Craft effective prompts for Microsoft Copilot" 
#### Step: 

Description of issue:  In the 'Craft effective prompts for Microsoft Copilot' module, screenshots are not displaying properly, leading to broken images in the instructions.

Repro steps:

![image](https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/assets/166609408/7f05a713-3da4-45bb-bf03-76a14f28bdaf)

**Comment by TesterTesterson1004** [comment]
Confirm issue, appears that the referenced /media dir is not present such that the markdown image links can work:

`![Screenshot of the Copilot panel in PowerPoint upon first opening.](../media/copilot-pane-powerpoint.png)`

**Comment by maquinl** [comment]
This issue has been resolved in the dev environment, pending release to production in the next few days or so.
