### ISSUE TITLE
Suggested improvement for customer facing instructions

### ISSUE THREAD

**Issue by MSFT-mengchong** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#10]
# Module: 00
#### Step: 00

Description of issue

Suggest improving customer facing instructions to be similar to the screenshot below from AZ-500.  This would make the format consistent with all other exercise instructions and have a single link to access all the sample data files.
![Screenshot 2024-06-04 155745](https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/assets/136421132/5bd8235c-c16f-448f-b729-e53d75fd753b)

**Comment by dahans-msft2** [comment]
@MSFT-mengchong Issue acknowledged, investigating how to deploy it this way.

**Comment by maquinl** [comment]
@MSFT-mengchong for now, we do not plan to reply on GitHub pages for this course as it not necessary - the instructions in this github repo are a 1:1 copy of the exercises from the learning path: https://learn.microsoft.com/en-us/training/paths/craft-effective-prompts-copilot-microsoft-365/
