### ISSUE TITLE
Sample prompt doesn't work in Word

### ISSUE THREAD

**Issue by MSFT-mengchong** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#11]
# Module: 03
#### Step: 03

Description of issue

The prompt "Visualize as a table" is not selectable and nor does it work when keyed in manually.  The following error is encountered.
![image](https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/assets/136421132/2dcf126d-b491-4cc3-ad2f-e1aba8015ce2)

Suggest changing the prompt to "Visualize /Graphic Design Institute - Employee benefits.doc as a table" instead.  The following is the output.
![image](https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/assets/136421132/1594e8f7-de56-42ee-a26d-02e3a1fd02e5)

**Comment by dahans-msft2** [comment]
@MSFT-mengchong Issue acknowledged.

The "Visualize as a table" option is only available after selecting a block of text on the contents of the Word document, not the text from the Copilot results.  The exercise has you copy the results from Copilot into the Word document and then highlight it to visualize as a table.

Can you confirm if that is the issue or another issue?  Thanks!
