### ISSUE TITLE
Create a Power Point from a Document does not work

### ISSUE THREAD

**Issue by Alfonsorodc** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#12]
# Module:Create and Draft Content
#### Step: 

Description of issue
The title is not aligned with the goal of this task. Also it does not work, we can not create a PowerPoint by referencing that document. It says that can not do that task. 

Repro steps:

1.
1.
1.

**Comment by dahans-msft2** [comment]
@Alfonsorodc Issue acknowledged.

Was the feature not available at all or not working as expected? Was the file you wanted to reference not available in the context menu?
