### ISSUE TITLE
M03 missing instruction #6

### ISSUE THREAD

**Issue by msftnutta** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#14]
# Module: 3
#### Step: 6

Description of issue

the markdown files list show a below, notice that #6 is missing.

![image](https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/assets/98095529/335a449e-274f-4ee0-9d75-b17708220d61)

Causing the empty page in CloudSlice as show below after hitting "next" button from step #5

![image](https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/assets/98095529/147b2e38-f18a-4902-9516-4991dfc6fcee)

Please rename #7 to #6

**Comment by dahans-msft2** [comment]
@msftnutta Issue acknowledged, will update when I have a resolution.
