### ISSUE TITLE
M04 - missing step #7

### ISSUE THREAD

**Issue by msftnutta** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#15]
# Module: 4

![image](https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/assets/98095529/bc4574f7-ad1f-4e8a-93f5-743fd761e1ab)

Similar to #14 but this is on Module 4

causing the empty page in CloudSlice's instruction.

**Comment by dahans-msft2** [comment]
@msftnutta Issue acknowledged, will update when I have a resolution.
