### ISSUE TITLE
Copilot in outlook- Login Issue: Attempting to sign in to the Outlook desktop app with lab user credentials results in failure.

### ISSUE THREAD

**Issue by PayalGuruprasad** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#2]
# Module: Copilot in outlook
#### Step: 

Description of issue:
Lab Access Issue: There's a login failure with the Outlook desktop app using lab credentials. Accessing Outlook via www.office.com is the current workaround

Repro steps:

1. Trying to login from the outlook windows app fails: 
![image](https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/assets/166609408/fce6d4a1-0164-4f10-91a6-04aad7b7661d)

Suggestion:
Specify using www.office.com for Outlook access in the lab instructions to avoid login issues with the desktop app

**Comment by maquinl** [comment]
Hi Payal - we do not specifically call out which app to use because the idea is that participants can use Outlook on the web, desktop, or mobile. 

However, we will investigate the issue with outlook desktop in the lab environment,

**Comment by PayalGuruprasad** [comment]
Thank you for the update @Matt ***@***.***>.

Regards,

Payal
