### ISSUE TITLE
Two sets of Instructions, one in /Instructions, one in /Allfiles - which is authoritative?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#3]
I currently see what appears to be 2 separate sets of Instructions, one is in the /Instructions path, while one is in the /Allfiles path.  Is this being done by-design?  I ask becuase traditionally in MOC/ESI courses, the authoritative lab Instructions will reside in /Instructions path in GH.

On the other hand, traditionally, the /Allfiles dir is reserved for non-instructional content associated with the lab such as sample code, json files or ARM templates, or otherwise containing items *not* the actual Instructions markdown files.

**Comment by maquinl** [comment]
This has been resolved, thanks.
