### ISSUE TITLE
Simplify the download of reference files for lab environment

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#4]
# LP: 02
### Lab: all
Description of issue
When working on the labs inside the VMs hosted by a provider (e.g. Skillable) I have to copy each link for the reference file manually into the browser of the VM and download the files separately. It would be much nicer to have a link in the instructions to copy all files easily from within the VM.

One option would be to offer the link to the Microsoft Learn page with the files for each module, for example for module 1:
https://learn.microsoft.com/training/modules/summarize-simplify-information-with-microsoft-copilot-microsoft-365/1a-follow-along-using-sample-data-copilot-microsoft-365
Then the learner can open this one link in the browser and save each file directly into the OneDrive of the lab user.

**Comment by dahans-msft2** [comment]
@mkennten Issue acknowledged, investigating solution.

**Comment by maquinl** [comment]
@mkennten 

Within the skillable enviornment, selecting the green text with a "T" symbol before it should autofill the address bar within edge

![image](https://github.com/user-attachments/assets/e08acf65-a73f-4f94-be35-860ba05ac85c)

If you do not see this, i would suggest opening an issue with the ALH.
