### ISSUE TITLE
LP2-Mod2-Provide PowerPoint demo file

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#5]
# LP: 02
#### Task: PowerPoint prompts

Description of issue
For the previous and following steps demo files are provided (Word, Excel) but no PowerPoint file. The instructions don't mention if there should be a file to be used from the set of demo files (there is no PPTX file) or if the learner should use a PowerPoint of their own.

Please clarify instructions and provide a sample PPTX file to allow for the same experience as with the other M365 apps.

**Comment by msftnutta** [comment]
#13 reported as well, but it's duplicate

@maquinl @geschwei @calvin-m-y-y Please have a look at this.

**Comment by dahans-msft2** [comment]
@mkennten Issue acknowledged, investigating solution.
