### ISSUE TITLE
LP2-Mod1-Excel prompt doesn't work due to lack of information in table

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#6]
# LP: 02
### Task: Excel analysis

Description of issue
The prompt doesn't work since the table doesn't provide information about products (at least not clear enough for Copilot) and stores.

Repro steps:

1. Open Contoso Chai Tea market trends 2023.xlsx
1. Enter this prompt:

Analyze this Excel table. We're looking for the top selling products from May through August to inform our marketing strategy for next year. Please highlight the top selling product for each store and month.
1. Note the answer of Copilot that it cannot do what was asked due to missing information in the table (rightfully).

![image](https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/assets/37703728/756d8ad8-4082-4dd0-80cc-2f9956c72491)

**Comment by dahans-msft2** [comment]
@mkennten Issue acknowledged, investigating solution.
