### ISSUE TITLE
catch-up-prepare-week-copilot-outlook: Update the instructions for outlook copilot as the feature to modify summary is no longer available 

### ISSUE THREAD

**Issue by PayalGuruprasad** [MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365#9]
# Module: M01-Summarize-simplify-information-with-microsoft-copilot-microsoft-365
#### Step: https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/blob/master/Instructions/Labs/M01-Summarize-simplify-information-with-microsoft-copilot-microsoft-365/6-catch-up-prepare-week-copilot-outlook.md#lets-get-crafting

Description of issue: Summarize this email conversation.
The summarize feature in Outlook no longer has the option to edit/modify the generated summary

So the following steps need to be updated: as this feature is no longer available 

![image](https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/assets/166609408/e3e1bc7e-3376-435f-ba4e-159b994a5ebd)

Repro steps:

1. When accessing the summarize option on outlook there is no way to modify or edit the summary 

![image](https://github.com/MicrosoftLearning/MS-4005-Craft-effective-prompts-for-Microsoft-Copilot-for-Microsoft-365/assets/166609408/6e04c338-a133-4749-999a-4632f854fd80)

Expectation:

Update the instructions for outlook copilot as the feature to modify summary is no longer available

**Comment by dahans-msft2** [comment]
@PayalGuruprasad Issue acknowledged, investigating solution.
